### ISSUE TITLE
order of applications change by moving it to different screen

### ISSUE THREAD

**Issue by onyxde** [kaspermeerts/BottomPanel#1]
I am using: gnome-shell/extensions/Bottom_Panel@rmy.pobox.com
I do not know if its you.
1) Assume you have two monitors.
2) assume you have two terminals open.
3) mind the application order of the bottom line.
4) move on terminal application to an different monitor.
5) the order of application swaps!

Note: I have ungrouped applications.

Regards,

**Comment by kaspermeerts** [comment]
Sorry, that is not me.

His site can be found here: http://frippery.org/extensions/
There is a mail address at the bottom of the page

Good luck
